### ISSUE TITLE
Multiple Inputs Compatibility

### ISSUE THREAD

**Issue by simonMoisselin** [testingautomated-usi/uncertainty-wizard#37]
Hello,

Nice project !

I am trying to make it work for a multi-input keras model, represented by a list of numpy arrays. 

Unfortunately, I am getting this following error:

```
ValueError: At the moment, uwiz stochastic models support only (unbatched)numpy arrays and tf.data.Datasets as inputs. Please transform your input in one of these forms
```

Is there any workaround for making this project work for multi-input?

**Comment by MiWeiss** [comment]
Hi @simonMoisselin 

Thanks a lot for your interest in uncertainty-wizard.

As of now, multi-input stochastic models are not yet supported, but supporting them should just be after a small patch. I'm working on it today and will probably be able to push a version for you to test by tomorrow.

Best,
Michael

**Comment by MiWeiss** [comment]
Hi @simonMoisselin 

Can you try if the following meets your needs?


1. Get the prepared patch
```
pip install git+https://github.com/testingautomated-usi/uncertainty-wizard.git@multi-input-tfds
```
2. Transform your inputs into a 'tf.data.Dataset'. This will allow the patched `uwiz` model to broadcast your input to your sample size, and should equivalent to the keras model as the list of arrays, afaik.
```
# Your test data
your_data: List[np.ndarray] = ....
# Convert them to individual tf.data.Dataset
atomic_ds: List[tf.data.Dataset] = [ tf.data.Dataset.from_tensor_slices(x) for x in your_data]
# Combine them into a single dataset
dataset: tf.data.Dataset = tf.data.Dataset.zip(atomic_ds)
```

3. Call uwiz 
```
your_model.predict_quantified(dataset, ...)
```

**Comment by simonMoisselin** [comment]
Hi @MiWeiss I have just tried and I am getting this error with the following code:

```python
X_inp = [tf.data.Dataset.from_tensor_slices(x) for x in X_inp]
X_inp = tuple(X_inp)
dataset = tf.data.Dataset.zip(X_inp)

stochastic_model = uwiz.models.stochastic_from_keras(m)
stochastic_model.predict_quantified(dataset, 
                                    quantifier='var_ratio',
                                    sample_size=16)
```
```
 ValueError: Data is expected to be in format `x`, `(x,)`, `(x, y)`, or `(x, y, sample_weight)`, found: (<tf.Tensor 'IteratorGetNext:0' shape=(----) dtype=float64>, <tf.Tensor 'IteratorGetNext:1' shape=(------) dtype=float64>, <tf.Tensor 'IteratorGetNext:2' shape=(------) dtype=float64>, <tf.Tensor 'IteratorGetNext:3' shape=(-----) dtype=float64>, <tf.Tensor 'IteratorGetNext:4' shape=(----) dtype=float64>, <tf.Tensor 'IteratorGetNext:5' shape=(None, 3) dtype=float64>)

```

Also, I need to transform the list of tf.data.Dataset into tuple otherwise I am getting this error


```
TypeError: The argument to `Dataset.zip()` must be a nested structure of `Dataset` objects. Nested structures do not support Python lists; please use a tuple instead.
```

My tensorflow version is `'2.3.1'`

**Comment by MiWeiss** [comment]
Thanks for your fast reply. Sorry for missing the thing about the tuples vs. list - I didn't notice the zip function was that picky ;-)

As for the ValueError, this one is a bit more difficult to erase; it appears not actually a problem of uncertainty-wizard, but of tf.keras, which appears not to be able to interpret the input. While I faced a different error than you, I was getting it to work using named inputs (note the map function):

```python
        # Dummy Model
        inputs = [tf.keras.Input((1,), name="a"), tf.keras.Input((1,), name="b")]
        combined = inputs[0] + inputs[1]
        dropped = tf.keras.layers.Dropout(0.5)(combined)
        output = tf.keras.layers.Dense(1)(dropped)
        model = tf.keras.Model(inputs=inputs, outputs=output)

        # Dummy Dataset
        dataset = tf.data.Dataset.zip((
            tf.data.Dataset.from_tensor_slices(tf.zeros((10, 1))),
            tf.data.Dataset.from_tensor_slices(tf.ones((10, 1))),
        )).map(lambda a, b: {"a": a, "b": b})

        stochastic_model = uwiz.models.stochastic_from_keras(model)
        pred, unc = stochastic_model.predict_quantified(dataset,
                                                        quantifier='var_ratio',
                                                        sample_size=16)
        print(pred)
        print(unc)
        
        # Exit 0 
```

If you send me a bit more info about your model (e.g. the input layers, if that's not confidential), I'll further try to reproduce the error. 

To give you a bit more context about the bug (why we're using tf.data): `uncertainty-wizard` needs to repeat every input `sample_size` many times. For memory reasons, this is done on-the-fly on a stream, i.e., on a tf.data.Dataset. 

Dependent on your input data (given that they are numpy array, and your sample size is 16, I assume it's not too much), the simplest solution would just be to inflate your numpy arrays in `X_inp` with a factor of 16. I don't want to do this as part of a library, as it is likely to lead to unexpected memory problems for any user not aware of these internals. But a flag on `predict_quantified` to disable the input 'repetition' in `predict_quantify` would allow you to pass in the inflated arrays, which would be directed directly into the model's predict call. I've been thinking about smth along these lines for a while, to support a much wider range of use cases in general, and this issue might just be the proper motivation if we can't find another solution.

**Comment by MiWeiss** [comment]
Multiple-Inputs previously failed as uwiz was not able to broadcast the inputs num_samples times. Now, multiple inputs can be handled by injecting a custom broadcaster. ( #43 )

Hence, this is now (with some manual effort) supported - without having to merge a large amount of hard to maintain code.
